all:
  hosts:

    devapp01:

      ansible_host: 10.10.1.20

      controlm_enabled: true
      splunk_enabled: true
      otel_enabled: true
      connectdirect_enabled: false

    devapp02:

      ansible_host: 10.10.1.21

      controlm_enabled: true
      splunk_enabled: false
      otel_enabled: true
      connectdirect_enabled: true